### ISSUE TITLE
Configuration for VimL?

### ISSUE THREAD

**Issue by mosheavni** [styx-meiseles/abbreinder.nvim#18]
Hi, the documentation only have the LUA config,
For a LUA noob, can you please share a VImL config to bootstrap the plugin?
Thanks :)

**Comment by 0styx0** [comment]
Yes, I’ll do that tomorrow.

Apr 27, 2022, 04:34 by ***@***.***:

**Comment by 0styx0** [comment]
had a bit of free time today so added instructions for vim-plug to the README. if you're using a different plugin manager you should be able to convert it easily enough, if not then let me know:)

Note: while testing, I noticed that when using vim-plug the `BufRead` autocmd is necessary, but it is not necessary when using packer. As I don't use vim-plug and the workaround is essentially a one-liner, I don't care to debug the difference in behavior. If someone wants, PRs welcome.
